### ISSUE TITLE
Iterators for the SparseMap

### ISSUE THREAD

**Issue by LesleyLai** [LesleyLai/Beyond-Game-Engine#7]
`SparseMap` should have both non-const and const iterators.

https://github.com/LesleyLai/Beyond-Game-Engine/blob/1050615ed73fe3210ecc61a33b06d36f9f907b2e/Engine/core/include/core/ecs/sparse_map.hpp#L40-L188

**Comment by liyutommy** [comment]
Need to research how to implement `->` operator on proxy `std::pair`

**Comment by LesleyLai** [comment]
Resolved
